"""Atualizando model  leitura

Revision ID: 1c18536fbdb1
Revises: 736da1dfb251
Create Date: 2025-04-19 23:13:32.504118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c18536fbdb1'
down_revision = '736da1dfb251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leitura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('id_uanque', sa.UUID(), nullable=True))
        batch_op.drop_constraint('leitura_id_Usuario_fkey', type_='foreignkey')
        batch_op.drop_constraint('leitura_id_Tanque_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['id_usuario'], ['id'])
        batch_op.create_foreign_key(None, 'tanque', ['id_uanque'], ['id'])
        batch_op.drop_column('id_Usuario')
        batch_op.drop_column('id_Tanque')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leitura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_Tanque', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id_Usuario', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('leitura_id_Tanque_fkey', 'tanque', ['id_Tanque'], ['id'])
        batch_op.create_foreign_key('leitura_id_Usuario_fkey', 'usuario', ['id_Usuario'], ['id'])
        batch_op.drop_column('id_uanque')
        batch_op.drop_column('id_usuario')

    # ### end Alembic commands ###
