"""Criando Perfil

Revision ID: 230a1e7b3636
Revises: 
Create Date: 2025-04-03 19:06:15.612369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '230a1e7b3636'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permissao_perfil')
    op.drop_table('permissao')
    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissoes', postgresql.ARRAY(sa.String()), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.drop_column('permissoes')

    op.create_table('permissao',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('permissao_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome', postgresql.ENUM('USUARIO_LISTAR', 'USUARIO_DETALHAR', 'USUARIO_CRIAR', 'USUARIO_EDITAR', 'USUARIO_EXCLUIR', 'PERFIL_LISTAR', 'PERFIL_DETALHAR', 'PERFIL_CRIAR', 'PERFIL_EDITAR', 'PERFIL_EXCLUIR', 'PERMISSAO_LISTAR', 'PERMISSAO_DETALHAR', 'PERMISSAO_CRIAR', 'PERMISSAO_EXCLUIR', 'TANQUE_LISTAR', 'TANQUE_DETALHAR', 'TANQUE_CRIAR', 'TANQUE_EDITAR', 'TANQUE_EXCLUIR', 'SENSOR_LISTAR', 'SENSOR_DETALHAR', 'SENSOR_CRIAR', 'SENSOR_EDITAR', 'SENSOR_EXCLUIR', 'LEITURA_LISTAR', 'LEITURA_DETALHAR', 'LEITURA_POR_TANQUE', 'LEITURA_POR_SENSOR', 'LEITURA_CRIAR', 'LEITURA_EXCLUIR', name='permissionenum'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='permissao_pkey'),
    sa.UniqueConstraint('nome', name='permissao_nome_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('permissao_perfil',
    sa.Column('perfil_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permissao_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.id'], name='permissao_perfil_perfil_id_fkey'),
    sa.ForeignKeyConstraint(['permissao_id'], ['permissao.id'], name='permissao_perfil_permissao_id_fkey'),
    sa.PrimaryKeyConstraint('perfil_id', 'permissao_id', name='permissao_perfil_pkey')
    )
    # ### end Alembic commands ###
