"""Usuario Update

Revision ID: 31ce0306cb52
Revises: 
Create Date: 2025-04-05 21:30:35.823217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ce0306cb52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_login', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('senha_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('senha_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('google_login')

    # ### end Alembic commands ###
