"""Usuario adicionado ao tanque

Revision ID: 4c062c1a9ff7
Revises: 7adabb32e2aa
Create Date: 2025-04-19 00:26:04.292400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c062c1a9ff7'
down_revision = '7adabb32e2aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tanque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'usuario', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tanque', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
