"""Cria as tabelas no novo banco de dados

Revision ID: 6c7dca071c5f
Revises: 5d230c78a091
Create Date: 2025-04-18 23:37:26.862090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7dca071c5f'
down_revision = '5d230c78a091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tanque',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('propriedade_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['propriedade_id'], ['propriedade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tanque')
    # ### end Alembic commands ###
