"""Atualizando model  leitura

Revision ID: 736da1dfb251
Revises: f7b6bf180960
Create Date: 2025-04-19 22:30:09.067834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736da1dfb251'
down_revision = 'f7b6bf180960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leitura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('valor',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('id_Usuario',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('id_Tanque',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('id_propriedade',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leitura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.alter_column('id_propriedade',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('id_Tanque',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('id_Usuario',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('valor',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
