"""Atualizando model  leitura 2

Revision ID: a46d75f02603
Revises: 1c18536fbdb1
Create Date: 2025-04-19 23:15:42.384083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46d75f02603'
down_revision = '1c18536fbdb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leitura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_tanque', sa.UUID(), nullable=True))
        batch_op.drop_constraint('leitura_id_uanque_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tanque', ['id_tanque'], ['id'])
        batch_op.drop_column('id_uanque')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leitura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_uanque', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('leitura_id_uanque_fkey', 'tanque', ['id_uanque'], ['id'])
        batch_op.drop_column('id_tanque')

    # ### end Alembic commands ###
