"""Novas Correção na sensor_model e tanque_model

Revision ID: be010c2e6d9b
Revises: d5bb8f51a367
Create Date: 2025-04-27 17:02:22.186539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be010c2e6d9b'
down_revision = 'd5bb8f51a367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.drop_constraint('sensor_tanque_criacao_id_fkey', type_='foreignkey')
        batch_op.drop_column('tanque_criacao_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanque_criacao_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('sensor_tanque_criacao_id_fkey', 'tanque', ['tanque_criacao_id'], ['id'])

    # ### end Alembic commands ###
