"""Adiciona colunas de detalhes da água à leitura

Revision ID: cfffec8f4287
Revises: a46d75f02603
Create Date: 2025-04-26 22:01:35.676337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfffec8f4287'
down_revision = 'a46d75f02603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leitura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cor_agua', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('oxigenio', sa.Float(), nullable=False, server_default='0.0')) 
        batch_op.add_column(sa.Column('temperatura', sa.Float(), nullable=False, server_default='0.0')) 
        batch_op.add_column(sa.Column('ph_agua', sa.Float(), nullable=False, server_default='0.0'))    
        batch_op.add_column(sa.Column('amonia', sa.Float(), nullable=False, server_default='0.0'))     

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leitura', schema=None) as batch_op:
        batch_op.drop_column('amonia')
        batch_op.drop_column('ph_agua')
        batch_op.drop_column('temperatura')
        batch_op.drop_column('oxigenio')
        batch_op.drop_column('cor_agua')

    # ### end Alembic commands ###
