"""Correção na sensor_model

Revision ID: d5bb8f51a367
Revises: eef02de28a7b
Create Date: 2025-04-27 16:25:52.738407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5bb8f51a367'
down_revision = 'eef02de28a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.alter_column('tanque_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('tanque_criacao_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.alter_column('tanque_criacao_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('tanque_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
