"""Adiciona relacionamento tanque-sensor

Revision ID: eef02de28a7b
Revises: 67fb2441e308
Create Date: 2025-04-27 15:45:51.220298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef02de28a7b'
down_revision = '67fb2441e308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanque_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('tanque_criacao_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'tanque', ['tanque_criacao_id'], ['id'])
        batch_op.create_foreign_key(None, 'tanque', ['tanque_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tanque_criacao_id')
        batch_op.drop_column('tanque_id')

    # ### end Alembic commands ###
