"""Criar tabela leitura

Revision ID: f7b6bf180960
Revises: 4c062c1a9ff7
Create Date: 2025-04-19 21:12:22.242402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b6bf180960'
down_revision = '4c062c1a9ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leitura',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('valor', sa.String(), nullable=False),
    sa.Column('id_Usuario', sa.UUID(), nullable=False),
    sa.Column('id_Tanque', sa.UUID(), nullable=False),
    sa.Column('id_propriedade', sa.UUID(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_Tanque'], ['tanque.id'], ),
    sa.ForeignKeyConstraint(['id_Usuario'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['id_propriedade'], ['propriedade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leitura')
    # ### end Alembic commands ###
